
--- Iniciando módulo de relatórios em 2025-05-08 10:25:56.184355 ---
Diretório da aplicação: c:\Users\Marco-Note\Desktop\PythonProject\Sistema
Caminhos no sys.path: ['c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\python310.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\Marco-Note\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv\\lib\\site-packages']

--- Iniciando módulo de relatórios em 2025-05-09 09:47:15.525424 ---
Diretório da aplicação: c:\Users\Marco-Note\Desktop\PythonProject\Sistema
Caminhos no sys.path: ['c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\python310.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\Marco-Note\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv\\lib\\site-packages']
ERRO AO OBTER VENDAS: ('Error while preparing SQL statement:\n- SQLCODE: -104\n- Dynamic SQL Error\n- SQL error code = -104\n- Token unknown - line 9, column 35\n- LIMIT', -104, 335544569)
ERRO AO OBTER VENDAS: ('Error while preparing SQL statement:\n- SQLCODE: -104\n- Dynamic SQL Error\n- SQL error code = -104\n- Token unknown - line 9, column 35\n- LIMIT', -104, 335544569)

--- Iniciando módulo de relatórios em 2025-05-12 10:01:08.897064 ---
Diretório da aplicação: c:\Users\Marco-Note\Desktop\PythonProject\Sistema
Caminhos no sys.path: ['c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\python310.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\Marco-Note\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv\\lib\\site-packages', 'c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\PDV']
ERRO AO OBTER VENDAS: ('Error while preparing SQL statement:\n- SQLCODE: -104\n- Dynamic SQL Error\n- SQL error code = -104\n- Token unknown - line 9, column 35\n- LIMIT', -104, 335544569)

--- Iniciando módulo de relatórios em 2025-05-12 11:48:15.393963 ---
Diretório da aplicação: c:\Users\Marco-Note\Desktop\PythonProject\Sistema
Caminhos no sys.path: ['c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\python310.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\Marco-Note\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv\\lib\\site-packages']

--- Iniciando módulo de relatórios em 2025-05-12 14:13:20.220999 ---
Diretório da aplicação: c:\Users\Marco-Note\Desktop\PythonProject\Sistema
Caminhos no sys.path: ['c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\python310.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\Marco-Note\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv\\lib\\site-packages']
ERRO AO OBTER VENDAS: ('Error while preparing SQL statement:\n- SQLCODE: -104\n- Dynamic SQL Error\n- SQL error code = -104\n- Token unknown - line 9, column 35\n- LIMIT', -104, 335544569)

--- Iniciando módulo de relatórios em 2025-05-12 14:18:00.837740 ---
Diretório da aplicação: c:\Users\Marco-Note\Desktop\PythonProject\Sistema
Caminhos no sys.path: ['c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\python310.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\Marco-Note\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv\\lib\\site-packages']

--- Iniciando módulo de relatórios em 2025-05-12 14:25:38.786521 ---
Diretório da aplicação: c:\Users\Marco-Note\Desktop\PythonProject\Sistema
Caminhos no sys.path: ['c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\python310.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\Marco-Note\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv\\lib\\site-packages', 'c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema']

--- Iniciando módulo de relatórios em 2025-05-12 14:33:24.155787 ---
Diretório da aplicação: c:\Users\Marco-Note\Desktop\PythonProject\Sistema
Caminhos no sys.path: ['c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\PDV', 'c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\python310.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\Marco-Note\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv', 'C:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema\\.venv\\lib\\site-packages', 'c:\\Users\\Marco-Note\\Desktop\\PythonProject\\Sistema']
